### ISSUE TITLE
How to redirect

### ISSUE THREAD

**Issue by siddheshthipse** [ShemiNechmad/GoogleSignInAngular#2]
How to redirect to different page in case of successful sign in? The router.navigate doesnt work inside handleCredentialResponse()
For that matter none of the other custom functions are getting called from that handleCredentialResponse()

**Comment by ShemiNechmad** [comment]
Hi,
If you need other dependencies, I think it's better to leave all the method in the callback.
For example, something like this:
```
callback: (response: any) => {
     get credentials.... if successful...
     this.route.navigate(['somewhere']);
     etc..
}
```
See last update in app.component.ts file.

**Comment by ShemiNechmad** [comment]
@siddheshthipse 
**Another update**
I changed the callback syntax, so you can use other dependencies in the method.
Have a look at the app.component.ts file.
Now you can navigate in the function (better with ngZone).

```
callback: (response: any) => this.handleGoogleSignIn(response)

handleGoogleSignIn(response: any) {
     ...
}
```

**Comment by siddheshthipse** [comment]
It wasn't working normally but after using NgZone inside `handleGoogleSignIn`
`this.zone.run(() => {
      this.router.navigate(['home-page']);
    });`
It worked as expected
Thanks a lot @ShemiNechmad for the quick support
